### ISSUE TITLE
Missing RL.ppo Function and Dataset Format for part_obs_u_dof_2_1000_iter

### ISSUE THREAD

**Issue by Veraepe** [Ceaser626/Parafoil_landing_with_DRL#2]
I was looking through your repository, and I noticed that the implementation of the RL.ppo function seems to be missing. Also, I couldn't find details on the format of the part_obs_u_dof_2_1000_iter dataset. Could you clarify these points for me?

Thank you for your help!

**Comment by Ceaser626** [comment]
Hi there, the RL.ppo function is uploaded. As for the format of the part_obs_u_dof_2_1000_iter dataset, it can be found in RL.ppo.py.
